// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.0
// source: api.proto

package keypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyDiffChangeType int32

const (
	KeyDiffChangeType_UNSPECIFIED KeyDiffChangeType = 0
	KeyDiffChangeType_INSERT      KeyDiffChangeType = 1
	KeyDiffChangeType_UPDATE      KeyDiffChangeType = 2
	KeyDiffChangeType_DELETION    KeyDiffChangeType = 3
)

// Enum value maps for KeyDiffChangeType.
var (
	KeyDiffChangeType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INSERT",
		2: "UPDATE",
		3: "DELETION",
	}
	KeyDiffChangeType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INSERT":      1,
		"UPDATE":      2,
		"DELETION":    3,
	}
)

func (x KeyDiffChangeType) Enum() *KeyDiffChangeType {
	p := new(KeyDiffChangeType)
	*p = x
	return p
}

func (x KeyDiffChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyDiffChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (KeyDiffChangeType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x KeyDiffChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyDiffChangeType.Descriptor instead.
func (KeyDiffChangeType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type KeyDiffOverview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inserts   int64 `protobuf:"varint,1,opt,name=inserts,proto3" json:"inserts,omitempty"`
	Updates   int64 `protobuf:"varint,2,opt,name=updates,proto3" json:"updates,omitempty"`
	Deletions int64 `protobuf:"varint,3,opt,name=deletions,proto3" json:"deletions,omitempty"`
}

func (x *KeyDiffOverview) Reset() {
	*x = KeyDiffOverview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyDiffOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDiffOverview) ProtoMessage() {}

func (x *KeyDiffOverview) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDiffOverview.ProtoReflect.Descriptor instead.
func (*KeyDiffOverview) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *KeyDiffOverview) GetInserts() int64 {
	if x != nil {
		return x.Inserts
	}
	return 0
}

func (x *KeyDiffOverview) GetUpdates() int64 {
	if x != nil {
		return x.Updates
	}
	return 0
}

func (x *KeyDiffOverview) GetDeletions() int64 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

type KeyDiffChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type  KeyDiffChangeType `protobuf:"varint,3,opt,name=type,proto3,enum=keypb.KeyDiffChangeType" json:"type,omitempty"`
}

func (x *KeyDiffChange) Reset() {
	*x = KeyDiffChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyDiffChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDiffChange) ProtoMessage() {}

func (x *KeyDiffChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDiffChange.ProtoReflect.Descriptor instead.
func (*KeyDiffChange) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *KeyDiffChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyDiffChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyDiffChange) GetType() KeyDiffChangeType {
	if x != nil {
		return x.Type
	}
	return KeyDiffChangeType_UNSPECIFIED
}

type KeyDiffChanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changes []*KeyDiffChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *KeyDiffChanges) Reset() {
	*x = KeyDiffChanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyDiffChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDiffChanges) ProtoMessage() {}

func (x *KeyDiffChanges) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDiffChanges.ProtoReflect.Descriptor instead.
func (*KeyDiffChanges) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *KeyDiffChanges) GetChanges() []*KeyDiffChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type KeyDiff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*KeyDiff_Changes
	//	*KeyDiff_Overview
	Content isKeyDiff_Content `protobuf_oneof:"content"`
}

func (x *KeyDiff) Reset() {
	*x = KeyDiff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDiff) ProtoMessage() {}

func (x *KeyDiff) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDiff.ProtoReflect.Descriptor instead.
func (*KeyDiff) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (m *KeyDiff) GetContent() isKeyDiff_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *KeyDiff) GetChanges() *KeyDiffChanges {
	if x, ok := x.GetContent().(*KeyDiff_Changes); ok {
		return x.Changes
	}
	return nil
}

func (x *KeyDiff) GetOverview() *KeyDiffOverview {
	if x, ok := x.GetContent().(*KeyDiff_Overview); ok {
		return x.Overview
	}
	return nil
}

type isKeyDiff_Content interface {
	isKeyDiff_Content()
}

type KeyDiff_Changes struct {
	Changes *KeyDiffChanges `protobuf:"bytes,1,opt,name=changes,proto3,oneof"`
}

type KeyDiff_Overview struct {
	Overview *KeyDiffOverview `protobuf:"bytes,2,opt,name=overview,proto3,oneof"`
}

func (*KeyDiff_Changes) isKeyDiff_Content() {}

func (*KeyDiff_Overview) isKeyDiff_Content() {}

type SendKeyDiffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyDiff *KeyDiff `protobuf:"bytes,1,opt,name=key_diff,json=keyDiff,proto3" json:"key_diff,omitempty"`
}

func (x *SendKeyDiffRequest) Reset() {
	*x = SendKeyDiffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyDiffRequest) ProtoMessage() {}

func (x *SendKeyDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyDiffRequest.ProtoReflect.Descriptor instead.
func (*SendKeyDiffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *SendKeyDiffRequest) GetKeyDiff() *KeyDiff {
	if x != nil {
		return x.KeyDiff
	}
	return nil
}

type SendKeyDiffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendKeyDiffResponse) Reset() {
	*x = SendKeyDiffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyDiffResponse) ProtoMessage() {}

func (x *SendKeyDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyDiffResponse.ProtoReflect.Descriptor instead.
func (*SendKeyDiffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6b, 0x65, 0x79,
	0x70, 0x62, 0x22, 0x63, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x4f, 0x76, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x65, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x44, 0x69,
	0x66, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x40,
	0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66,
	0x66, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x22, 0x7d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x12, 0x31, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b,
	0x65, 0x79, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x34,
	0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66,
	0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x3f, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x64, 0x69, 0x66,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e,
	0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66,
	0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x4a, 0x0a, 0x11, 0x4b, 0x65, 0x79, 0x44, 0x69,
	0x66, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x03, 0x32, 0x5a, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79,
	0x44, 0x69, 0x66, 0x66, 0x12, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4b, 0x65, 0x79, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x44,
	0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42,
	0x10, 0x5a, 0x0e, 0x65, 0x74, 0x63, 0x64, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x6b, 0x65, 0x79, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []interface{}{
	(KeyDiffChangeType)(0),      // 0: keypb.KeyDiffChangeType
	(*KeyDiffOverview)(nil),     // 1: keypb.KeyDiffOverview
	(*KeyDiffChange)(nil),       // 2: keypb.KeyDiffChange
	(*KeyDiffChanges)(nil),      // 3: keypb.KeyDiffChanges
	(*KeyDiff)(nil),             // 4: keypb.KeyDiff
	(*SendKeyDiffRequest)(nil),  // 5: keypb.SendKeyDiffRequest
	(*SendKeyDiffResponse)(nil), // 6: keypb.SendKeyDiffResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: keypb.KeyDiffChange.type:type_name -> keypb.KeyDiffChangeType
	2, // 1: keypb.KeyDiffChanges.changes:type_name -> keypb.KeyDiffChange
	3, // 2: keypb.KeyDiff.changes:type_name -> keypb.KeyDiffChanges
	1, // 3: keypb.KeyDiff.overview:type_name -> keypb.KeyDiffOverview
	4, // 4: keypb.SendKeyDiffRequest.key_diff:type_name -> keypb.KeyDiff
	5, // 5: keypb.KeyPushService.SendKeyDiff:input_type -> keypb.SendKeyDiffRequest
	6, // 6: keypb.KeyPushService.SendKeyDiff:output_type -> keypb.SendKeyDiffResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyDiffOverview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyDiffChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyDiffChanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyDiff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyDiffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyDiffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*KeyDiff_Changes)(nil),
		(*KeyDiff_Overview)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
